### ISSUE TITLE
Problème de chargement des fichiers CSS

### ISSUE THREAD

**Issue by rafutek** [dbarzin/mercator#690]
Bonjour,

Je suis en train de tester une installation de Mercator sur une machine virtuelle via Docker Compose, la page de login s'affiche mais les fichiers CSS ne sont pas récupérés et je ne comprends pas pourquoi. Serait-il possible de m'aider ?

![image](https://github.com/dbarzin/mercator/assets/47695845/ba1f8341-6239-440f-a761-c06ec3c4aea6)

fichier .env :
```
APP_NAME=Mercator
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://mercator.domain.test

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=mercator
DB_USERNAME=mercator
DB_PASSWORD=mercator

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
```

fichier docker-compose.yml :
```yml
services:
  mercator:
    image: ghcr.io/dbarzin/mercator:latest
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    container_name: mercator
    volumes:
      - ./.env:/var/www/mercator/.env
    # entrypoint: /bin/sleep 3600 # pour debug
    environment:
      - DB_CONNECTION=$DB_CONNECTION
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - APP_ENV=$APP_ENV
      - USE_DEMO_DATA=1
      - APP_URL=http://mercator.domain.test/
      - ASSET_URL=http://mercator.domain.test/
    ports:
      - 8000:80
    networks:
      - local

  db:
    image: mysql:latest
    restart: unless-stopped
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
    networks:
      - local
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

networks:
  local:
```

Merci d'avance
