### ISSUE TITLE
Image Docker multi-platforme ?

### ISSUE THREAD

**Issue by tvalero35678** [dbarzin/mercator#727]
Bonjour,

Toujours pour faciliter le déploiement rapide d'une version de démonstration, pourriez-vous aussi construire les **images Docker multi-plateforme**, donc avec aussi l'architecture ARM (linux/arm64) ? 

Sinon, pour déployer une version de démonstration sur un Mac récent (puce Apple), il faut reconstruire l'image, ce qui demande une petite technicité.

Cordialement,

T.

PS : merci pour la correction du petit bug de chargement des données de démonstration ( #721 ). Ça fonctionne chez moi.

**Comment by dbarzin** [comment]
Je ne suis pas très à l'aise avec Docker, mais je vais voir ce que je peux faire.

**Comment by asiffer** [comment]
@dbarzin Je pense qu'il suffit d'ajouter les plateformes désirées dans `.github/workflows/docker.yaml` (en espérant que le worker github arrive à cross-build 🤞🏻):
```yaml
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64 # <----
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
```
