### ISSUE TITLE
Bug, connexion impossible + changement de mot de passe impossible

### ISSUE THREAD

**Issue by naif0s** [dbarzin/mercator#814]
Bonjour,

J'ai installer Mercator avec Docker & Traefik, La documentation de mercator n'est vraiment pas simple. Il y a 2 docker-compose de chaque côté (dans 2 dossiers différents) cela amène à confusion. 

J'ai connecté mon LDAP et j'ai testé avec "php artisan ldap:test" qui arrive à se connecter. OK.

J'arrive à avoir accès à la page de connexion, mais les login de connexion par défaut ne fontionne pas :  These identifiers are not recognized. 

J'ai tenté de reset le mot de passe et : 

![image](https://github.com/user-attachments/assets/21dc3141-01ef-4e39-9286-f041c81f134e)

La requête : 

```
curl "https://mercator.XXX.com/password/reset" \
   -X GET \
   -H 'x-forwarded-server: cff1123f3c50' \
   -H 'x-forwarded-proto: https' \
   -H 'x-forwarded-port: 443' \
   -H 'x-forwarded-host: mercator.XXX.com' \
   -H 'upgrade-insecure-requests: 1' \
   -H 'te: trailers' \
   -H 'sec-fetch-user: ?1' \
   -H 'sec-fetch-site: same-origin' \
   -H 'sec-fetch-mode: navigate' \
   -H 'sec-fetch-dest: document' \
   -H 'referer: https://mercator.XXX.com/login' \
   -H 'priority: u=0, i' \
   -H 'cookie: <CENSORED>' \
   -H 'accept-language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' \
   -H 'accept-encoding: gzip, deflate, br' \
   -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8' \
   -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0' \
   -H 'host: mercator.XXX.com';
```

Sinon voici mon docker-compose : 

```
services:
  mercator:
    image: ghcr.io/dbarzin/mercator:latest
    restart: unless-stopped
    container_name: mercator
    volumes:
      - /data/mercator/volumes/databases/db.sqlite/:/var/www/mercator/sql/db.sqlite
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.mercator-http.rule=Host(`mercator.XXX.com`)
      - traefik.http.routers.mercator-http.entrypoints=web
      - traefik.http.routers.mercator-http.middlewares=redirect-to-https@file
      - traefik.http.routers.mercator.rule=Host(`mercator.XXX.com`)
      - traefik.http.routers.mercator.entrypoints=websecure
      - traefik.http.routers.mercator.tls=true
      - traefik.http.routers.mercator.tls.certresolver=tomandjerry
      - traefik.http.middlewares.add-forwarded-headers.headers.sslRedirect=true
      - traefik.http.middlewares.add-forwarded-headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.add-forwarded-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.add-forwarded-headers.headers.stsPreload=true
      - traefik.http.middlewares.add-forwarded-headers.headers.stsSeconds=31536000
      - traefik.http.middlewares.add-forwarded-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.add-forwarded-headers.headers.customresponseheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.add-forwarded-headers.headers.customrequestheaders.X-Forwarded-For=${CLIENT_IP}
      - traefik.http.middlewares.add-forwarded-headers.headers.customrequestheaders.X-Real-IP=${CLIENT_IP}
      - traefik.http.routers.mercator.middlewares=add-forwarded-headers@docker
    environment:
      ##########################################
      # CONFIG set to your company's domain name
      - APP_URL=https://mercator.XXX.com
      - ASSET_URL=https://mercator.XXX.com/
      ##########################################

      ##########################################
      # uncomment if you want to load demo data
      # - USE_DEMO_DATA=1
      ##########################################

      # - Plusieurs types possibles : AD, OpenLDAP, FreeIPA, DirectoryServer
      - LDAP_TYPE="AD"
      # - # If true, LDAP actions will be written to the application's default log file
      # - LDAP_LOGGING=true
      - LDAP_CONNECTION=default
      - LDAP_HOST=srv-ad
      # - # Identifiers of the user who will connect to the LDAP in order to perform queries
      - LDAP_USERNAME="XXX\ldap"
      - LDAP_PASSWORD=XXX
      - LDAP_PORT=389
      - LDAP_BASE_DN="OU=Users,OU=XXX,DC=xxx,DC=lan"
      - LDAP_TIMEOUT=5
      - LDAP_SSL=false
      - LDAP_TLS=false
      # - # Allows you to restrict access to a tree structure
      # - LDAP_SCOPE="ou=Accounting,ou=Groups,dc=planetexpress,dc=com"
      # - # Allows you to restrict access to groups
      # - LDAP_GROUPS="Delivering,Help Desk"
      - APP_ENV=production
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
```
