### ISSUE TITLE
Auth issue

### ISSUE THREAD

**Issue by mxmchr** [dbarzin/mercator#863]
Bonjour,
Je suis en train d'effecteur des tests sur mercator sur différentes installations via docker compose.
depuis hier soir, quand je déploie mes conteneurs nginx et mercator, j'arrive sur la page de login, et je ne peux pas m'authentifier.
J'ai recommencé au propre ce soir, mais je rencontre la même erreur.
J'ai décidé d'aller voir dans la base sqlite, je vois bien la structure de la base de données, mais les tables sont totalement vide malgré la variable :
- USE_DEMO_DATA=1 dans mon compose.

![image](https://github.com/user-attachments/assets/0d1f97ab-3606-430f-af2f-5001cd757f55)

![auth mercator](https://github.com/user-attachments/assets/820a6b44-d0a1-4ffa-84d7-0b429c95e4da)

Voici mon yml :

```yml
version: '3.7'
services:
  reverse-proxy:
    image: nginx:latest
    restart: unless-stopped
    container_name: reverse-proxy
    volumes:
      - ./PV/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./PV/nginx/certs:/etc/nginx/certs
      ##########################################
      # uncomment if you need your company's CA root certificate (don't forget to change the certificate name)
      - ./PV/nginx/myCompany.crt:/usr/local/share/ca-certificates/CA.crt
      - ./PV/nginx/update-ca-certificates.sh:/docker-entrypoint.d/1000-update-ca-certificates.sh
      ##########################################

    ports:
      - 443:443
    depends_on:
      - mercator

  mercator:
    image: ghcr.io/dbarzin/mercator:latest
    restart: unless-stopped
    container_name: mercator
    volumes:
      - ./PV/mercator/db.sqlite/:/var/www/mercator/sql/db.sqlite
      - ./env/mercator.env:/var/www/mercator/.env
      - ../app/Http/Kernel.php:/var/www/mercator/app/Http/Kernel.php
      - ../app/Http/Middleware/ForceXForwardedProto.php:/var/www/mercator/app/Http/Middleware/ForceXForwardedProto.php
    expose:
      - 80
    environment:
      ##########################################
      # CONFIG set to your company's domain name
      - APP_URL=https://carto.lab.local/
      - ASSET_URL=https://carto.lab.local/
      ##########################################

      ##########################################
      # uncomment if you want to load demo data
      - USE_DEMO_DATA=1
      ##########################################

      # - Plusieurs types possibles : AD, OpenLDAP, FreeIPA, DirectoryServer
      - LDAP_TYPE="AD"
      # - # If true, LDAP actions will be written to the application's default log file
      - LDAP_LOGGING=true
      - LDAP_CONNECTION=default
      - LDAP_HOST=10.0.0.1
      # - # Identifiers of the user who will connect to the LDAP in order to perform queries
      - LDAP_USERNAME="dn=administrateur,cn=user,dc=lab,dc=local"
      - LDAP_PASSWORD=secret
      - LDAP_PORT=636
      - LDAP_BASE_DN="dc=lab,dc=local"
      # - LDAP_TIMEOUT=5
      - LDAP_SSL=true
      # - LDAP_TLS=false
      # - # Allows you to restrict access to a tree structure
      # - LDAP_SCOPE="ou=Accounting,ou=Groups,dc=planetexpress,dc=com"
      # - # Allows you to restrict access to groups
      # - LDAP_GROUPS="Delivering,Help Desk"
```
